{{- if and .Values.ingress.enable .Values.ingress.acme }}
{{- $root := . }}
{{- $httpLocation := .Values.ingress.path }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ template "anycableGo.fullname" $root }}-acme"
  annotations:
    kubernetes.io/tls-acme: "true"
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  tls:
  - hosts:
{{- range $host := .Values.ingress.acme.hosts }}
    - {{ $host | quote }}
{{- end }}
    secretName: "{{ template "anycableGo.fullname" $root }}-tls-acme"
  rules:
{{- range $host := .Values.ingress.acme.hosts }}
  - host: {{ $host | quote }}
    http:
      paths:
      - path: {{ $httpLocation | quote }}
        backend:
          serviceName: "{{ template "anycableGo.fullname" $root }}"
          servicePort: 80
{{- end }}
{{- end }}
