{{- if and .Values.ingress.enable .Values.ingress.acme }}
{{- $releaseName := .Release.Name }}
{{- $httpLocation := .Values.ingress.path }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ $releaseName }}-ingress-acme"
  annotations:
    kubernetes.io/tls-acme: "true"
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  tls:
  - hosts:
{{- range $host := .Values.ingress.acme.hosts }}
    - {{ $host | quote }}
{{- end }}
    secretName: "{{ $releaseName }}-tls-acme"
  rules:
{{- range $host := .Values.ingress.acme.hosts }}
  - host: {{ $host | quote }}
    http:
      paths:
      - path: {{ $httpLocation | quote }}
        backend:
          serviceName: {{ $releaseName | quote }}
          servicePort: 80
{{- end }}
{{- end }}
