{{- if and .Values.ingress.enable .Values.ingress.nonAcme.hosts }}
{{- $root := . }}
{{- $httpLocation := .Values.ingress.path }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ template "anycableGo.fullname" $root }}"
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  tls:
{{- range $secret := .Values.ingress.nonAcme.hosts }}
  - hosts:
{{- range $host := $secret.names }}
    - {{ $host | quote }}
{{- end }}
    secretName: {{ $secret.secretName | quote }}
{{- end }}
  rules:
{{- range $secret := .Values.ingress.nonAcme.hosts }}
{{- range $host := $secret.names }}
  - host: {{ $host | quote }}
    http:
      paths:
      - path: {{ $httpLocation | quote }}
        backend:
          serviceName: "{{ template "anycableGo.fullname" $root }}"
          servicePort: 80
{{- end }}
{{- end }}
{{- end }}
