apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "anycableGo.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  name: {{ template "anycableGo.fullname" . }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: {{ .Values.env.anycablePort }}
  selector:
    app: {{ template "anycableGo.name" . }}
    component: anycable-go
    release: {{ .Release.Name | quote }}
  type: ClusterIP
